cloud:
  gateway:
    routes:
      - id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE
        predicates:
          -path=/employee/**
        filters:
          - AddRequestHeader=employee-request, employee-request-header
            - AddResponseHeader=employee-response, employee-response-header

      - id: ADMIN-SERVICE
        uri: lb://ADMIN-SERVICE
        predicates:
          -path=/admin/**
        filters:
          - AddRequestHeader=admin-request, admin-request-header
            - AddResponseHeader=admin-response, admin-response-header


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8762

spring:
  application:
    name: Api-Gateway